---
title: "Exam 2 Study Guide"
format: html
---

## Topics To Know For The Exam

-   How can bias affect modeling

-   What an outlier is

-   What is an influential outlier and when should we consider them

-   What assumptions do

-   Main assumptions

-   How to assess

    -   Linearity

    -   Normality

    -   Homoscedasticity

    -   Independence of residuals

-   Know if your data needs to be normally distributed

    -   What should be normally distributed

-   How the central limit theorem involved in modeling

-   Know what and how homoscedasticity affects models

-   Know what homoscedasticity and heteroscedasticity are

    -   What are options if you have heteroscedasticity

-   What independence is

-   Know the difference between a p-p plot and a q-q plot

-   What are the problems with statistical tests for testing normality assumption

-   How to spot issues with normality and independence

    -   How should visuals look for these assumptions

-   Know how to write out statistics in text form

-   What can be done with bias in your data

-   How to deal with violated assumptions

-   Know the difference between independent-samples t-test and paired-samples t-test

-   Know how t-tests are included in the linear model

-   Know what a dummy variable

    -   Know what the values are for dummy variables

-   Know what the intercept in a linear model is (t-test only)

-   Know what a Welch t-test and how its different from a Student's t-test

-   Know the interpretation of a t-test

    -   What does it mean to have a significant finding

-   What is the issue of running multiple t-tests

    -   What will happen if we run 20 tests and find one statistical finding

-   Know why we remove population means from calculations

-   Know how to calculate independent-samples t-test, paired-samples t-test, and one-way ANOVA

-   Know what the variance sum law is

-   Know what is missing from equations/formulas

-   Know what formulas/equations mean

-   Know what needs to be done when groups are different for independent-samples t-tests

-   Know the designs of each test (between-subjects, within-subjects)

-   Know the difference in the formulas for a paired-samples t-test

-   Know the difference in the distributions between the t-test distributions

-   Know the standard error of differences

-   Know how to calculate effect sizes for all tests

    -   Know size of correlation effect sizes

-   Difference between ANOVA and independent-samples t-test

-   Know how to read all the tables (studentized, t, F)

-   Know what a reference group

-   Know what an ANOVA can't do compared to a linear regression

-   Know how to formulate both a null hypothesis and an alternative hypothesis

-   Know, generally, the difference between a planned contrast and a post-hoc analysis

-   Know what a F-test tells us and what it doesn't tell us

-   Know when to check post-hoc findings

-   Know what a grand mean is compared to group means

-   Know what the total, model, and residual sum of squares

-   Know the difference between sum of squares and mean squares

-   Know what each degrees of freedom are and what they are used for

-   Know what a F-test is compared to the specific comparisons

-   Know how to calculate a Tukey Honestly Significant Difference Test

-   Know how to tell if a finding is statistically significant

-   Know what can be done to data suffering heterogeneity/heteroscedasticity for a F-test

-   What can be done to correct model parameters that may violate assumptions for F-tests

-   Know, generally, what orthogonal vs non-orthogonal contrasts are

-   Know how many curves in a line equal what trend is trying to be shown

-   Know what happens when there are too many curves in a trend line

-   Know when to use the Least-Significant Difference comparison

-   Know what post-hoc tests are the most balanced

-   Know the difference between $R^2$ and $\eta^2$